import getpass
import os
date = ""
last_frame = 0


def output_dic(items: list) -> dict:
    dic = {
        "FilePath": rf"C:\Users\{getpass.getuser()}\works\sumiwataturo\PF\{date}.ymmp",
        "Timeline": {
            "VideoInfo": {"FPS": 60, "Hz": 48000, "Width": 1920, "Height": 1080},
            "VerticalLine": {
                "IsEnabled": False,
                "StartFrame": 0,
                "LineType": "BPM",
                "Line": {
                    "$type": "YukkuriMovieMaker.Project.VerticalBPMLine, YukkuriMovieMaker.General",
                    "BPM": 100,
                },
                "Group": 4,
            },
            "Items": items,
            "LayerSettings": {"Items": []},
            "CurrentFrame": 0,
            "Length": last_frame,
            "MaxLayer": 9,
        },
        "Characters": [
            {
                "Name": "霊夢",
                "GroupName": "その他",
                "Color": "#FFFF0000",
                "Layer": 0,
                "Voice": {"API": "AquesTalk", "Arg": "f1"},
                "Volume": {
                    "From": 100.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "Pan": {"From": 0.0, "To": 0.0, "AnimationType": "なし", "Span": 0.0},
                "PlaybackRate": 100.0,
                "VoiceParameter": {
                    "$type": "YukkuriMovieMaker.Voice.VoiceParameter, YukkuriMovieMaker",
                    "Speed": 110,
                },
                "AdditionalTime": 0.4,
                "VoiceFadeIn": 0.0,
                "VoiceFadeOut": 0.0,
                "EchoIsEnabled": False,
                "EchoInterval": 0.1,
                "EchoAttenuation": 40.0,
                "CustomVoiceIsEnabled": False,
                "CustomVoiceIncludeSubdirectories": False,
                "CustomVoiceDirectory": "",
                "CustomVoiceFileName": "",
                "IsJimakuVisible": True,
                "IsJimakuLocked": False,
                "X": {"From": 0.0, "To": 0.0, "AnimationType": "なし", "Span": 0.0},
                "Y": {"From": 380.0, "To": 0.0, "AnimationType": "なし", "Span": 0.0},
                "Opacity": {
                    "From": 100.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "Zoom": {"From": 100.0, "To": 0.0, "AnimationType": "なし", "Span": 0.0},
                "Rotation": {
                    "From": 0.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "JimakuFadeIn": 0.0,
                "JimakuFadeOut": 0.0,
                "Blend": "Normal",
                "IsInverted": False,
                "IsAlwaysOnTop": False,
                "IsClippingWithObjectAbove": False,
                "Font": "けいふぉんと",
                "FontSize": {
                    "From": 80.0,
                    "To": 1.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "LineHeight2": {
                    "From": 125.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "LetterSpacing2": {
                    "From": 0.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "DisplayInterval": 0.0,
                "BasePoint": "CenterCenter",
                "FontColor": "#FFFFFFFF",
                "Style": "Border",
                "StyleColor": "#FFFF0000",
                "Bold": False,
                "Italic": False,
                "IsDevidedPerCharacter": False,
                "JimakuVideoEffects": [],
                "TachieType": "YukkuriMovieMaker.Plugin.Tachie.AnimationTachie.AnimationTachiePlugin, YukkuriMovieMaker.Plugin.Tachie.AnimationTachie, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                "TachieCharacterParameter": {
                    "$type": "YukkuriMovieMaker.Plugin.Tachie.AnimationTachie.CharacterParameter, YukkuriMovieMaker.Plugin.Tachie.AnimationTachie",
                    "Directory": f"{os.path.expanduser('~')}\\ゆっくり動画\\キャラ素材\\れいむ_cw_anime\\yukkuri",
                    "EyeBlinkStart": 0.0,
                    "EyeBlinkInterval": 0.0,
                    "MouthSensitivity": 100.0,
                },
                "IsTachieLocked": False,
                "TachieX": {
                    "From": -750.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "TachieY": {
                    "From": -10.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "TachieOpacity": {
                    "From": 100.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "TachieZoom": {
                    "From": 150.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "TachieRotation": {
                    "From": 0.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "TachieFadeIn": 0.0,
                "TachieFadeOut": 0.0,
                "TachieBlend": "Normal",
                "TachieIsInverted": True,
                "TachieIsAlwaysOnTop": False,
                "TachieIsClippingWithObjectAbove": False,
                "TachieDefaultItemParameter": {
                    "$type": "YukkuriMovieMaker.Plugin.Tachie.AnimationTachie.ItemParameter, YukkuriMovieMaker.Plugin.Tachie.AnimationTachie",
                    "IsHiddenWhenNoSpeech": False,
                    "Eyebrow": f"{os.path.expanduser('~')}\\ゆっくり動画\\キャラ素材\\れいむ_cw_anime\\yukkuri\\眉\\00.png",
                    "Eye": f"{os.path.expanduser('~')}\\ゆっくり動画\\キャラ素材\\れいむ_cw_anime\\yukkuri\\目\\00.png",
                    "Mouth": f"{os.path.expanduser('~')}\\ゆっくり動画\\キャラ素材\\れいむ_cw_anime\\yukkuri\\口\\00.png",
                    "Hair": None,
                    "Complexion": None,
                    "Body": f"{os.path.expanduser('~')}\\ゆっくり動画\\キャラ素材\\れいむ_cw_anime\\yukkuri\\体\\00.png",
                    "Back1": None,
                    "Back2": None,
                    "Back3": None,
                    "Etc1": None,
                    "Etc2": None,
                    "Etc3": None,
                },
                "TachieItemVideoEffects": [
                    {
                        "$type": "YukkuriMovieMaker.Project.Effects.RepeatMoveEffect, YukkuriMovieMaker",
                        "Label": "反復移動 X0px, Y40px, 2.00秒",
                        "X": {
                            "From": 0.0,
                            "To": 0.0,
                            "AnimationType": "なし",
                            "Span": 0.0,
                        },
                        "Y": {
                            "From": 40.0,
                            "To": 0.0,
                            "AnimationType": "なし",
                            "Span": 0.0,
                        },
                        "Span": {
                            "From": 2.0,
                            "To": 0.0,
                            "AnimationType": "なし",
                            "Span": 0.0,
                        },
                        "EasingType": "Sine",
                        "EasingMode": "InOut",
                        "IsCentering": True,
                        "IsEnabled": True,
                    }
                ],
                "TachieDefaultFaceParameter": {
                    "$type": "YukkuriMovieMaker.Plugin.Tachie.AnimationTachie.FaceParameter, YukkuriMovieMaker.Plugin.Tachie.AnimationTachie",
                    "EyeAnimation": "Default",
                    "MouthAnimation": "Default",
                    "Eyebrow": None,
                    "Eye": None,
                    "Mouth": None,
                    "Hair": None,
                    "Complexion": None,
                    "Body": None,
                    "Back1": None,
                    "Back2": None,
                    "Back3": None,
                    "Etc1": None,
                    "Etc2": None,
                    "Etc3": None,
                },
                "TachieDefaultFaceEffects": [],
                "AdditionalForegroundTemplateName": None,
                "AdditionalBackgroundTemplateName": None,
            },
            {
                "Name": "魔理沙",
                "GroupName": "その他",
                "Color": "#FFFFFF00",
                "Layer": 0,
                "Voice": {"API": "AquesTalk", "Arg": "f2"},
                "Volume": {
                    "From": 100.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "Pan": {"From": 0.0, "To": 0.0, "AnimationType": "なし", "Span": 0.0},
                "PlaybackRate": 100.0,
                "VoiceParameter": {
                    "$type": "YukkuriMovieMaker.Voice.VoiceParameter, YukkuriMovieMaker",
                    "Speed": 110,
                },
                "AdditionalTime": 0.4,
                "VoiceFadeIn": 0.0,
                "VoiceFadeOut": 0.0,
                "EchoIsEnabled": False,
                "EchoInterval": 0.1,
                "EchoAttenuation": 40.0,
                "CustomVoiceIsEnabled": False,
                "CustomVoiceIncludeSubdirectories": False,
                "CustomVoiceDirectory": "",
                "CustomVoiceFileName": "",
                "IsJimakuVisible": True,
                "IsJimakuLocked": False,
                "X": {"From": 0.0, "To": 0.0, "AnimationType": "なし", "Span": 0.0},
                "Y": {"From": 380.0, "To": 0.0, "AnimationType": "なし", "Span": 0.0},
                "Opacity": {
                    "From": 100.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "Zoom": {"From": 100.0, "To": 0.0, "AnimationType": "なし", "Span": 0.0},
                "Rotation": {
                    "From": 0.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "JimakuFadeIn": 0.0,
                "JimakuFadeOut": 0.0,
                "Blend": "Normal",
                "IsInverted": False,
                "IsAlwaysOnTop": False,
                "IsClippingWithObjectAbove": False,
                "Font": "けいふぉんと",
                "FontSize": {
                    "From": 80.0,
                    "To": 1.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "LineHeight2": {
                    "From": 125.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "LetterSpacing2": {
                    "From": 0.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "DisplayInterval": 0.0,
                "BasePoint": "CenterCenter",
                "FontColor": "#FFFFFFFF",
                "Style": "Border",
                "StyleColor": "#FF0000FF",
                "Bold": False,
                "Italic": False,
                "IsDevidedPerCharacter": False,
                "JimakuVideoEffects": [],
                "TachieType": "YukkuriMovieMaker.Plugin.Tachie.AnimationTachie.AnimationTachiePlugin, YukkuriMovieMaker.Plugin.Tachie.AnimationTachie, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                "TachieCharacterParameter": {
                    "$type": "YukkuriMovieMaker.Plugin.Tachie.AnimationTachie.CharacterParameter, YukkuriMovieMaker.Plugin.Tachie.AnimationTachie",
                    "Directory": f"{os.path.expanduser('~')}\\ゆっくり動画\\キャラ素材\\まりさ_cw_anime\\まりさ",
                    "EyeBlinkStart": 0.0,
                    "EyeBlinkInterval": 0.0,
                    "MouthSensitivity": 100.0,
                },
                "IsTachieLocked": False,
                "TachieX": {
                    "From": 750.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "TachieY": {
                    "From": -10.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "TachieOpacity": {
                    "From": 100.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "TachieZoom": {
                    "From": 150.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "TachieRotation": {
                    "From": 0.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "TachieFadeIn": 0.0,
                "TachieFadeOut": 0.0,
                "TachieBlend": "Normal",
                "TachieIsInverted": False,
                "TachieIsAlwaysOnTop": False,
                "TachieIsClippingWithObjectAbove": False,
                "TachieDefaultItemParameter": {
                    "$type": "YukkuriMovieMaker.Plugin.Tachie.AnimationTachie.ItemParameter, YukkuriMovieMaker.Plugin.Tachie.AnimationTachie",
                    "IsHiddenWhenNoSpeech": False,
                    "Eyebrow": f"{os.path.expanduser('~')}\\ゆっくり動画\\キャラ素材\\まりさ_cw_anime\\まりさ\\眉\\00.png",
                    "Eye": f"{os.path.expanduser('~')}\\ゆっくり動画\\キャラ素材\\まりさ_cw_anime\\まりさ\\目\\00.png",
                    "Mouth": f"{os.path.expanduser('~')}\\ゆっくり動画\\キャラ素材\\まりさ_cw_anime\\まりさ\\口\\00.png",
                    "Hair": None,
                    "Complexion": None,
                    "Body": f"{os.path.expanduser('~')}\\ゆっくり動画\\キャラ素材\\まりさ_cw_anime\\まりさ\\体\\00.png",
                    "Back1": None,
                    "Back2": None,
                    "Back3": None,
                    "Etc1": None,
                    "Etc2": None,
                    "Etc3": None,
                },
                "TachieItemVideoEffects": [
                    {
                        "$type": "YukkuriMovieMaker.Project.Effects.RepeatMoveEffect, YukkuriMovieMaker",
                        "Label": "反復移動 X0px, Y40px, 2.00秒",
                        "X": {
                            "From": 0.0,
                            "To": 0.0,
                            "AnimationType": "なし",
                            "Span": 0.0,
                        },
                        "Y": {
                            "From": 40.0,
                            "To": 0.0,
                            "AnimationType": "なし",
                            "Span": 0.0,
                        },
                        "Span": {
                            "From": 2.0,
                            "To": 0.0,
                            "AnimationType": "なし",
                            "Span": 0.0,
                        },
                        "EasingType": "Sine",
                        "EasingMode": "InOut",
                        "IsCentering": True,
                        "IsEnabled": True,
                    }
                ],
                "TachieDefaultFaceParameter": {
                    "$type": "YukkuriMovieMaker.Plugin.Tachie.AnimationTachie.FaceParameter, YukkuriMovieMaker.Plugin.Tachie.AnimationTachie",
                    "EyeAnimation": "Default",
                    "MouthAnimation": "Default",
                    "Eyebrow": None,
                    "Eye": None,
                    "Mouth": None,
                    "Hair": None,
                    "Complexion": None,
                    "Body": None,
                    "Back1": None,
                    "Back2": None,
                    "Back3": None,
                    "Etc1": None,
                    "Etc2": None,
                    "Etc3": None,
                },
                "TachieDefaultFaceEffects": [],
                "AdditionalForegroundTemplateName": None,
                "AdditionalBackgroundTemplateName": None,
            },
            {
                "Name": "2人",
                "GroupName": "その他",
                "Color": "#FF00FF72",
                "Layer": 0,
                "Voice": {"API": "AquesTalk", "Arg": "f1"},
                "Volume": {
                    "From": 100.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "Pan": {"From": 0.0, "To": 0.0, "AnimationType": "なし", "Span": 0.0},
                "PlaybackRate": 100.0,
                "VoiceParameter": {
                    "$type": "YukkuriMovieMaker.Voice.VoiceParameter, YukkuriMovieMaker",
                    "Speed": 110,
                },
                "AdditionalTime": 0.4,
                "VoiceFadeIn": 0.0,
                "VoiceFadeOut": 0.0,
                "EchoIsEnabled": False,
                "EchoInterval": 0.1,
                "EchoAttenuation": 40.0,
                "CustomVoiceIsEnabled": False,
                "CustomVoiceIncludeSubdirectories": False,
                "CustomVoiceDirectory": "",
                "CustomVoiceFileName": "",
                "IsJimakuVisible": True,
                "IsJimakuLocked": False,
                "X": {"From": 0.0, "To": 0.0, "AnimationType": "なし", "Span": 0.0},
                "Y": {"From": 380.0, "To": 0.0, "AnimationType": "なし", "Span": 0.0},
                "Opacity": {
                    "From": 100.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "Zoom": {"From": 100.0, "To": 0.0, "AnimationType": "なし", "Span": 0.0},
                "Rotation": {
                    "From": 0.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "JimakuFadeIn": 0.0,
                "JimakuFadeOut": 0.0,
                "Blend": "Normal",
                "IsInverted": False,
                "IsAlwaysOnTop": False,
                "IsClippingWithObjectAbove": False,
                "Font": "けいふぉんと",
                "FontSize": {
                    "From": 80.0,
                    "To": 1.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "LineHeight2": {
                    "From": 125.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "LetterSpacing2": {
                    "From": 0.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "DisplayInterval": 0.0,
                "BasePoint": "CenterCenter",
                "FontColor": "#FFFFFFFF",
                "Style": "Border",
                "StyleColor": "#FFFF0000",
                "Bold": False,
                "Italic": False,
                "IsDevidedPerCharacter": False,
                "JimakuVideoEffects": [],
                "TachieType": "YukkuriMovieMaker.Plugin.Tachie.AnimationTachie.AnimationTachiePlugin, YukkuriMovieMaker.Plugin.Tachie.AnimationTachie, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                "TachieCharacterParameter": {
                    "$type": "YukkuriMovieMaker.Plugin.Tachie.AnimationTachie.CharacterParameter, YukkuriMovieMaker.Plugin.Tachie.AnimationTachie",
                    "Directory": f"{os.path.expanduser('~')}\\ゆっくり動画\\キャラ素材\\れいむ_cw_anime\\yukkuri",
                    "EyeBlinkStart": 0.0,
                    "EyeBlinkInterval": 0.0,
                    "MouthSensitivity": 100.0,
                },
                "IsTachieLocked": False,
                "TachieX": {
                    "From": -750.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "TachieY": {
                    "From": -10.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "TachieOpacity": {
                    "From": 100.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "TachieZoom": {
                    "From": 150.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "TachieRotation": {
                    "From": 0.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "TachieFadeIn": 0.0,
                "TachieFadeOut": 0.0,
                "TachieBlend": "Normal",
                "TachieIsInverted": True,
                "TachieIsAlwaysOnTop": False,
                "TachieIsClippingWithObjectAbove": False,
                "TachieDefaultItemParameter": {
                    "$type": "YukkuriMovieMaker.Plugin.Tachie.AnimationTachie.ItemParameter, YukkuriMovieMaker.Plugin.Tachie.AnimationTachie",
                    "IsHiddenWhenNoSpeech": False,
                    "Eyebrow": f"{os.path.expanduser('~')}\\ゆっくり動画\\キャラ素材\\れいむ_cw_anime\\yukkuri\\眉\\00.png",
                    "Eye": f"{os.path.expanduser('~')}\\ゆっくり動画\\キャラ素材\\れいむ_cw_anime\\yukkuri\\目\\00.png",
                    "Mouth": f"{os.path.expanduser('~')}\\ゆっくり動画\\キャラ素材\\れいむ_cw_anime\\yukkuri\\口\\00.png",
                    "Hair": None,
                    "Complexion": None,
                    "Body": f"{os.path.expanduser('~')}\\ゆっくり動画\\キャラ素材\\れいむ_cw_anime\\yukkuri\\体\\00.png",
                    "Back1": None,
                    "Back2": None,
                    "Back3": None,
                    "Etc1": None,
                    "Etc2": None,
                    "Etc3": None,
                },
                "TachieItemVideoEffects": [
                    {
                        "$type": "YukkuriMovieMaker.Project.Effects.RepeatMoveEffect, YukkuriMovieMaker",
                        "Label": "反復移動 X0px, Y40px, 2.00秒",
                        "X": {
                            "From": 0.0,
                            "To": 0.0,
                            "AnimationType": "なし",
                            "Span": 0.0,
                        },
                        "Y": {
                            "From": 40.0,
                            "To": 0.0,
                            "AnimationType": "なし",
                            "Span": 0.0,
                        },
                        "Span": {
                            "From": 2.0,
                            "To": 0.0,
                            "AnimationType": "なし",
                            "Span": 0.0,
                        },
                        "EasingType": "Sine",
                        "EasingMode": "InOut",
                        "IsCentering": True,
                        "IsEnabled": True,
                    }
                ],
                "TachieDefaultFaceParameter": {
                    "$type": "YukkuriMovieMaker.Plugin.Tachie.AnimationTachie.FaceParameter, YukkuriMovieMaker.Plugin.Tachie.AnimationTachie",
                    "EyeAnimation": "Default",
                    "MouthAnimation": "Default",
                    "Eyebrow": None,
                    "Eye": None,
                    "Mouth": None,
                    "Hair": None,
                    "Complexion": None,
                    "Body": None,
                    "Back1": None,
                    "Back2": None,
                    "Back3": None,
                    "Etc1": None,
                    "Etc2": None,
                    "Etc3": None,
                },
                "TachieDefaultFaceEffects": [],
                "AdditionalForegroundTemplateName": None,
                "AdditionalBackgroundTemplateName": None,
            },
            {
                "Name": "フェード",
                "GroupName": "その他",
                "Color": "#FFFFFFFF",
                "Layer": 0,
                "Voice": {"API": "AquesTalk", "Arg": "f1"},
                "Volume": {
                    "From": 100.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "Pan": {"From": 0.0, "To": 0.0, "AnimationType": "なし", "Span": 0.0},
                "PlaybackRate": 100.0,
                "VoiceParameter": {
                    "$type": "YukkuriMovieMaker.Voice.VoiceParameter, YukkuriMovieMaker",
                    "Speed": 110,
                },
                "AdditionalTime": 0.4,
                "VoiceFadeIn": 0.0,
                "VoiceFadeOut": 0.0,
                "EchoIsEnabled": False,
                "EchoInterval": 0.1,
                "EchoAttenuation": 40.0,
                "CustomVoiceIsEnabled": False,
                "CustomVoiceIncludeSubdirectories": False,
                "CustomVoiceDirectory": "",
                "CustomVoiceFileName": "",
                "IsJimakuVisible": True,
                "IsJimakuLocked": False,
                "X": {"From": 0.0, "To": 0.0, "AnimationType": "なし", "Span": 0.0},
                "Y": {"From": 380.0, "To": 0.0, "AnimationType": "なし", "Span": 0.0},
                "Opacity": {
                    "From": 100.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "Zoom": {"From": 100.0, "To": 0.0, "AnimationType": "なし", "Span": 0.0},
                "Rotation": {
                    "From": 0.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "JimakuFadeIn": 0.0,
                "JimakuFadeOut": 0.0,
                "Blend": "Normal",
                "IsInverted": False,
                "IsAlwaysOnTop": False,
                "IsClippingWithObjectAbove": False,
                "Font": "けいふぉんと",
                "FontSize": {
                    "From": 80.0,
                    "To": 1.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "LineHeight2": {
                    "From": 125.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "LetterSpacing2": {
                    "From": 0.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "DisplayInterval": 0.0,
                "BasePoint": "CenterCenter",
                "FontColor": "#FFFFFFFF",
                "Style": "Border",
                "StyleColor": "#FFFF0000",
                "Bold": False,
                "Italic": False,
                "IsDevidedPerCharacter": False,
                "JimakuVideoEffects": [],
                "TachieType": "YukkuriMovieMaker.Plugin.Tachie.AnimationTachie.AnimationTachiePlugin, YukkuriMovieMaker.Plugin.Tachie.AnimationTachie, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                "TachieCharacterParameter": {
                    "$type": "YukkuriMovieMaker.Plugin.Tachie.AnimationTachie.CharacterParameter, YukkuriMovieMaker.Plugin.Tachie.AnimationTachie",
                    "Directory": f"{os.path.expanduser('~')}\\ゆっくり動画\\キャラ素材\\れいむ_cw_anime\\yukkuri",
                    "EyeBlinkStart": 0.0,
                    "EyeBlinkInterval": 0.0,
                    "MouthSensitivity": 100.0,
                },
                "IsTachieLocked": False,
                "TachieX": {
                    "From": -750.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "TachieY": {
                    "From": -10.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "TachieOpacity": {
                    "From": 100.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "TachieZoom": {
                    "From": 150.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "TachieRotation": {
                    "From": 0.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "TachieFadeIn": 0.0,
                "TachieFadeOut": 0.0,
                "TachieBlend": "Normal",
                "TachieIsInverted": True,
                "TachieIsAlwaysOnTop": False,
                "TachieIsClippingWithObjectAbove": False,
                "TachieDefaultItemParameter": {
                    "$type": "YukkuriMovieMaker.Plugin.Tachie.AnimationTachie.ItemParameter, YukkuriMovieMaker.Plugin.Tachie.AnimationTachie",
                    "IsHiddenWhenNoSpeech": False,
                    "Eyebrow": f"{os.path.expanduser('~')}\\ゆっくり動画\\キャラ素材\\れいむ_cw_anime\\yukkuri\\眉\\00.png",
                    "Eye": f"{os.path.expanduser('~')}\\ゆっくり動画\\キャラ素材\\れいむ_cw_anime\\yukkuri\\目\\00.png",
                    "Mouth": f"{os.path.expanduser('~')}\\ゆっくり動画\\キャラ素材\\れいむ_cw_anime\\yukkuri\\口\\00.png",
                    "Hair": None,
                    "Complexion": None,
                    "Body": f"{os.path.expanduser('~')}\\ゆっくり動画\\キャラ素材\\れいむ_cw_anime\\yukkuri\\体\\00.png",
                    "Back1": None,
                    "Back2": None,
                    "Back3": None,
                    "Etc1": None,
                    "Etc2": None,
                    "Etc3": None,
                },
                "TachieItemVideoEffects": [
                    {
                        "$type": "YukkuriMovieMaker.Project.Effects.RepeatMoveEffect, YukkuriMovieMaker",
                        "Label": "反復移動 X0px, Y40px, 2.00秒",
                        "X": {
                            "From": 0.0,
                            "To": 0.0,
                            "AnimationType": "なし",
                            "Span": 0.0,
                        },
                        "Y": {
                            "From": 40.0,
                            "To": 0.0,
                            "AnimationType": "なし",
                            "Span": 0.0,
                        },
                        "Span": {
                            "From": 2.0,
                            "To": 0.0,
                            "AnimationType": "なし",
                            "Span": 0.0,
                        },
                        "EasingType": "Sine",
                        "EasingMode": "InOut",
                        "IsCentering": True,
                        "IsEnabled": True,
                    }
                ],
                "TachieDefaultFaceParameter": {
                    "$type": "YukkuriMovieMaker.Plugin.Tachie.AnimationTachie.FaceParameter, YukkuriMovieMaker.Plugin.Tachie.AnimationTachie",
                    "EyeAnimation": "Default",
                    "MouthAnimation": "Default",
                    "Eyebrow": None,
                    "Eye": None,
                    "Mouth": None,
                    "Hair": None,
                    "Complexion": None,
                    "Body": None,
                    "Back1": None,
                    "Back2": None,
                    "Back3": None,
                    "Etc1": None,
                    "Etc2": None,
                    "Etc3": None,
                },
                "TachieDefaultFaceEffects": [],
                "AdditionalForegroundTemplateName": None,
                "AdditionalBackgroundTemplateName": None,
            },
            {
                "Name": "タイトル",
                "GroupName": "その他",
                "Color": "#FF00E4FF",
                "Layer": 0,
                "Voice": {"API": "AquesTalk", "Arg": "f1"},
                "Volume": {
                    "From": 100.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "Pan": {"From": 0.0, "To": 0.0, "AnimationType": "なし", "Span": 0.0},
                "PlaybackRate": 100.0,
                "VoiceParameter": {
                    "$type": "YukkuriMovieMaker.Voice.VoiceParameter, YukkuriMovieMaker",
                    "Speed": 110,
                },
                "AdditionalTime": 0.4,
                "VoiceFadeIn": 0.0,
                "VoiceFadeOut": 0.0,
                "EchoIsEnabled": False,
                "EchoInterval": 0.1,
                "EchoAttenuation": 40.0,
                "CustomVoiceIsEnabled": False,
                "CustomVoiceIncludeSubdirectories": False,
                "CustomVoiceDirectory": "",
                "CustomVoiceFileName": "",
                "IsJimakuVisible": True,
                "IsJimakuLocked": False,
                "X": {"From": 0.0, "To": 0.0, "AnimationType": "なし", "Span": 0.0},
                "Y": {"From": 380.0, "To": 0.0, "AnimationType": "なし", "Span": 0.0},
                "Opacity": {
                    "From": 100.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "Zoom": {"From": 100.0, "To": 0.0, "AnimationType": "なし", "Span": 0.0},
                "Rotation": {
                    "From": 0.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "JimakuFadeIn": 0.0,
                "JimakuFadeOut": 0.0,
                "Blend": "Normal",
                "IsInverted": False,
                "IsAlwaysOnTop": False,
                "IsClippingWithObjectAbove": False,
                "Font": "けいふぉんと",
                "FontSize": {
                    "From": 80.0,
                    "To": 1.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "LineHeight2": {
                    "From": 125.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "LetterSpacing2": {
                    "From": 0.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "DisplayInterval": 0.0,
                "BasePoint": "CenterCenter",
                "FontColor": "#FFFFFFFF",
                "Style": "Border",
                "StyleColor": "#FFFF0000",
                "Bold": False,
                "Italic": False,
                "IsDevidedPerCharacter": False,
                "JimakuVideoEffects": [],
                "TachieType": "YukkuriMovieMaker.Plugin.Tachie.AnimationTachie.AnimationTachiePlugin, YukkuriMovieMaker.Plugin.Tachie.AnimationTachie, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                "TachieCharacterParameter": {
                    "$type": "YukkuriMovieMaker.Plugin.Tachie.AnimationTachie.CharacterParameter, YukkuriMovieMaker.Plugin.Tachie.AnimationTachie",
                    "Directory": f"{os.path.expanduser('~')}\\ゆっくり動画\\キャラ素材\\れいむ_cw_anime\\yukkuri",
                    "EyeBlinkStart": 0.0,
                    "EyeBlinkInterval": 0.0,
                    "MouthSensitivity": 100.0,
                },
                "IsTachieLocked": False,
                "TachieX": {
                    "From": -750.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "TachieY": {
                    "From": -10.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "TachieOpacity": {
                    "From": 100.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "TachieZoom": {
                    "From": 150.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "TachieRotation": {
                    "From": 0.0,
                    "To": 0.0,
                    "AnimationType": "なし",
                    "Span": 0.0,
                },
                "TachieFadeIn": 0.0,
                "TachieFadeOut": 0.0,
                "TachieBlend": "Normal",
                "TachieIsInverted": True,
                "TachieIsAlwaysOnTop": False,
                "TachieIsClippingWithObjectAbove": False,
                "TachieDefaultItemParameter": {
                    "$type": "YukkuriMovieMaker.Plugin.Tachie.AnimationTachie.ItemParameter, YukkuriMovieMaker.Plugin.Tachie.AnimationTachie",
                    "IsHiddenWhenNoSpeech": False,
                    "Eyebrow": f"{os.path.expanduser('~')}\\ゆっくり動画\\キャラ素材\\れいむ_cw_anime\\yukkuri\\眉\\00.png",
                    "Eye": f"{os.path.expanduser('~')}\\ゆっくり動画\\キャラ素材\\れいむ_cw_anime\\yukkuri\\目\\00.png",
                    "Mouth": f"{os.path.expanduser('~')}\\ゆっくり動画\\キャラ素材\\れいむ_cw_anime\\yukkuri\\口\\00.png",
                    "Hair": None,
                    "Complexion": None,
                    "Body": f"{os.path.expanduser('~')}\\ゆっくり動画\\キャラ素材\\れいむ_cw_anime\\yukkuri\\体\\00.png",
                    "Back1": None,
                    "Back2": None,
                    "Back3": None,
                    "Etc1": None,
                    "Etc2": None,
                    "Etc3": None,
                },
                "TachieItemVideoEffects": [
                    {
                        "$type": "YukkuriMovieMaker.Project.Effects.RepeatMoveEffect, YukkuriMovieMaker",
                        "Label": "反復移動 X0px, Y40px, 2.00秒",
                        "X": {
                            "From": 0.0,
                            "To": 0.0,
                            "AnimationType": "なし",
                            "Span": 0.0,
                        },
                        "Y": {
                            "From": 40.0,
                            "To": 0.0,
                            "AnimationType": "なし",
                            "Span": 0.0,
                        },
                        "Span": {
                            "From": 2.0,
                            "To": 0.0,
                            "AnimationType": "なし",
                            "Span": 0.0,
                        },
                        "EasingType": "Sine",
                        "EasingMode": "InOut",
                        "IsCentering": True,
                        "IsEnabled": True,
                    }
                ],
                "TachieDefaultFaceParameter": {
                    "$type": "YukkuriMovieMaker.Plugin.Tachie.AnimationTachie.FaceParameter, YukkuriMovieMaker.Plugin.Tachie.AnimationTachie",
                    "EyeAnimation": "Default",
                    "MouthAnimation": "Default",
                    "Eyebrow": None,
                    "Eye": None,
                    "Mouth": None,
                    "Hair": None,
                    "Complexion": None,
                    "Body": None,
                    "Back1": None,
                    "Back2": None,
                    "Back3": None,
                    "Etc1": None,
                    "Etc2": None,
                    "Etc3": None,
                },
                "TachieDefaultFaceEffects": [],
                "AdditionalForegroundTemplateName": None,
                "AdditionalBackgroundTemplateName": None,
            },
        ],
        "CollapsedGroups": [],
    }

    return dic
